# Numpy Vs Lists
Numpy
- Same data type
- Store data very compactly
- Great for big numerical operations
- Consumes less mmemor and is convenient to use

Lists
- Different data type
- Less efficient
- Best for short codes

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

# ARRAY
- Is a central data structure of the Numpy library
- Is a grid of values and it contains informmation about the raw data, how to locate an element, and how to interpret an element.
- Has a grid of elements that can be indexed in varipus ways
- Elemments are all of the samme type, referred to as the array dtype
- An array can be indexed by a tuple of non-negative integers, by Booleans, by another array, or by integers


In [4]:
import numpy as np
a = np.array([5,5,5])
a

array([5, 5, 5])

In [5]:
type(a)

numpy.ndarray

In [8]:
# list of lists
import numpy as np
b = np.array([[5,5,5], [5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
type(b)

numpy.ndarray

# Vector vs Matrix
- Vector is an array with a single dimension no difference between row and columns
- Matrix an array with two dimension


In [10]:
len(b)

3

In [11]:
b[0]

array([5, 5, 5])

In [12]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# 3-D or higher
- The term TENSOR is commonly used
- Tensorflow is a free and open source software library for machine learning and artificial intelligence

In [14]:
import numpy as np
c = np.array([[5,5,5], [5,5,5]])
c

array([[5, 5, 5],
       [5, 5, 5]])

# How to create an array?


In [16]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [19]:
import numpy as np
b = np.zeros(2)
b

array([0., 0.])

In [20]:
c = np.ones(3)
c

array([1., 1., 1.])

In [21]:
d = np.empty(3)
d

array([1., 1., 1.])

In [22]:
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [23]:
# with specific range of elements
f = np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
# continue...
g = np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# linearly spaced arrays
h = np.linspace(0,10, num=5) #gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
# specific data types in array
# only integer array, 5 wota ek ek, datatype is integer
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [28]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

# 2-D arrays

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3-D array

In [32]:
# making and reshaping a 3D array
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])